version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      OPENAI_ORGANIZATION_ID: ${OPENAI_ORGANIZATION_ID}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PYTHONPATH: /app
