version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FILE_PATH: ${FILE_PATH}

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PYTHONPATH: /app
